import { useState } from "react";
import { TEMPLATE_SECTIONS, UPLOAD_TYPES } from '../../constants/index.js';
import { apiCall } from '../../api/index.js';
import DiffView from '../ui/DiffView.jsx';

function QuickUploadModal({company,onClose,onAccept,T}){
  var [txt,setTxt]=useState("");var [utype,setUtype]=useState("Earnings Report");var [loading,setLoading]=useState(false);var [diff,setDiff]=useState(null);var [meta,setMeta]=useState(null);
  async function run(){if(!txt.trim())return;setLoading(true);setDiff(null);setMeta(null);try{var allSecs=[...TEMPLATE_SECTIONS,"Earnings & Thesis Check"];var cur=allSecs.map(function(s){return"## "+s+"\n"+((company.sections&&company.sections[s])||"(empty)");}).join("\n\n");var r=await apiCall("Investment research assistant. New research ("+utype+") for "+company.name+" ("+company.ticker+"). Current template:\n"+cur+"\n\nReturn ONLY JSON: {changes:[{section,before,after,reason}],summary:string}. No markdown fences.",[{type:"text",text:txt}],2500);var parsed=JSON.parse(r.replace(/```json|```/g,"").trim());setDiff(parsed.changes||[]);setMeta({summary:parsed.summary,type:utype});}catch(e){alert("Could not process: "+e.message);}setLoading(false);}
  return(<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,0.4)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={onClose}><div onClick={function(e){e.stopPropagation();}} style={{background:T.bg,border:"1px solid "+T.border,borderRadius:12,padding:20,width:600,maxHeight:"85vh",overflowY:"auto",boxShadow:"0 8px 32px rgba(0,0,0,0.2)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><div style={{fontSize:14,fontWeight:600,color:T.text}}>Upload research — {company.name}</div><span onClick={onClose} style={{fontSize:12,color:T.textSec,cursor:"pointer"}}>✕</span></div><select value={utype} onChange={function(e){setUtype(e.target.value);}} style={{fontSize:12,padding:"6px 8px",borderRadius:6,border:"1px solid "+T.border,background:T.bg,color:T.text,marginBottom:8}}>{UPLOAD_TYPES.map(function(t){return <option key={t}>{t}</option>;})}</select><textarea value={txt} onChange={function(e){setTxt(e.target.value);}} placeholder="Paste research content..." style={{width:"100%",minHeight:120,resize:"vertical",fontSize:13,padding:"8px 10px",boxSizing:"border-box",borderRadius:6,border:"1px solid "+T.border,background:T.bg,color:T.text,fontFamily:"inherit",lineHeight:1.6,marginBottom:8}}/><button onClick={run} disabled={loading||!txt.trim()} style={{width:"100%",padding:"9px",fontWeight:500,marginBottom:12}}>{loading?"Analyzing...":"Analyze and propose updates"}</button>{diff&&meta&&(diff.length===0?<p style={{fontSize:13,color:T.textSec}}>No changes needed.</p>:<DiffView diff={diff} onAccept={function(){onAccept(company,diff,meta);onClose();}} onReject={function(){setDiff(null);setMeta(null);}} T={T}/>)}</div></div>);
}

export default QuickUploadModal;
