import { useState, useRef, useEffect } from "react";
import { TEMPLATE_SECTIONS } from '../../constants/index.js';
import { sectorStyle, shortSector } from '../../utils/index.js';

function TemplateSearch({companies,onSelect,onClose,T}){
  var [q,setQ]=useState("");var inp=useRef();
  useEffect(function(){if(inp.current)inp.current.focus();},[]);
  var allSections=[...TEMPLATE_SECTIONS,"Earnings & Thesis Check"];
  var results=q.trim().length<2?[]:companies.filter(function(c){return allSections.map(function(s){return(c.sections&&c.sections[s])||"";}).join(" ").toLowerCase().indexOf(q.toLowerCase())>=0;});
  return(<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,0.4)",zIndex:1000,display:"flex",alignItems:"flex-start",justifyContent:"center",paddingTop:80}} onClick={onClose}><div onClick={function(e){e.stopPropagation();}} style={{background:T.bg,border:"1px solid "+T.border,borderRadius:12,padding:20,width:520,maxHeight:"70vh",display:"flex",flexDirection:"column",boxShadow:"0 8px 32px rgba(0,0,0,0.2)"}}><div style={{fontSize:14,fontWeight:600,color:T.text,marginBottom:10}}>Search across all templates</div><input ref={inp} value={q} onChange={function(e){setQ(e.target.value);}} placeholder="Type at least 2 characters..." style={{fontSize:13,padding:"8px 10px",borderRadius:6,border:"1px solid "+T.border,background:T.bgSec,color:T.text,marginBottom:10}}/><div style={{overflowY:"auto",flex:1}}>{q.trim().length<2?<div style={{fontSize:12,color:T.textSec}}>Type at least 2 characters.</div>:results.length===0?<div style={{fontSize:12,color:T.textSec}}>No matches.</div>:results.map(function(c){var matching=allSections.filter(function(s){return(c.sections&&c.sections[s]||"").toLowerCase().indexOf(q.toLowerCase())>=0;});return(<div key={c.id} onClick={function(){onSelect(c,q);onClose();}} style={{padding:"10px 12px",borderRadius:8,border:"1px solid "+T.border,marginBottom:6,cursor:"pointer",background:T.bgSec}} onMouseEnter={function(e){e.currentTarget.style.background=T.bgTer;}} onMouseLeave={function(e){e.currentTarget.style.background=T.bgSec;}}><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:4}}><span style={{fontSize:13,fontWeight:500,color:T.text}}>{c.name}</span><span style={{fontSize:11,color:T.textSec}}>{c.ticker}</span>{c.sector&&(function(){var ss=sectorStyle(c.sector);return <span style={{fontSize:11,padding:"1px 6px",borderRadius:99,background:ss.bg,color:ss.color}}>{shortSector(c.sector)}</span>;}())}</div><div style={{fontSize:11,color:T.textSec}}>Found in: {matching.join(", ")}</div></div>);})}</div><div style={{marginTop:10,fontSize:12,color:T.textSec,textAlign:"right",cursor:"pointer"}} onClick={onClose}>Close (Esc)</div></div></div>);
}

export default TemplateSearch;
