import { useCompanyContext } from '../../context/CompanyContext.jsx';
import { PORTFOLIOS, TIER_ORDER } from '../../constants/index.js';
import { repShares, tierBg, tierPillStyle, tierToStatus, getTiers, truncName } from '../../utils/index.js';
import { PortPicker } from '../ui/index.js';

/* Portfolio Overlap subtab. Extracted from App.jsx verbatim; original inline
   IIFE referenced parent-scope variables via closure, now explicit props +
   context. */
export function OverlapTable(props){
  const { overlapMode, setOverlapMode, overlapFilter, setOverlapFilter,
          setSelCo, setTab, setCoView, setSelCoOrigin } = props;
  const { companies, repData, fxRates, specialWeights, dark, updateCo } = useCompanyContext();

var OVERLAP_ORDER=["FIN","IN","FGL","GL","EM","SC"];var OVERLAP_LABELS={"FIN":"FIN","IN":"IN","FGL":"FGL","GL":"GL","EM":"EM","SC":"SC"};var isRep=overlapMode==="rep";
/* Precompute rep weights per company per portfolio */
var repWts={};if(isRep){OVERLAP_ORDER.forEach(function(port){
  var portRep2=repData[port]||{};
  /* Build ticker-owner map: portfolio members claim first, then any other company */
  var owners={};
  companies.filter(function(c){return(c.portfolios||[]).indexOf(port)>=0;}).forEach(function(c){(c.tickers||[]).forEach(function(t){var tk=(t.ticker||"").toUpperCase();if(tk&&!owners[tk])owners[tk]=c.id;});});
  companies.filter(function(c){return(c.portfolios||[]).indexOf(port)<0;}).forEach(function(c){(c.tickers||[]).forEach(function(t){var tk=(t.ticker||"").toUpperCase();if(tk&&!owners[tk])owners[tk]=c.id;});});
  var total=0;
  companies.forEach(function(c){var seen2={};(c.tickers||[]).forEach(function(t){var tk=(t.ticker||"").toUpperCase();if(!tk||seen2[tk]||owners[tk]!==c.id)return;seen2[tk]=true;var shares=repShares(portRep2[tk]);if(shares&&t.price){var ccy=(t.currency||"USD").toUpperCase();var fx=ccy==="USD"?1:(fxRates[ccy]||0);if(fx>0)total+=shares*parseFloat(t.price)/fx;}});});
  total+=repShares(portRep2["CASH"])+repShares(portRep2["DIVACC"]);
  repWts[port]={};
  if(total>0){companies.forEach(function(c){var mv=0;var seen2={};(c.tickers||[]).forEach(function(t){var tk=(t.ticker||"").toUpperCase();if(!tk||seen2[tk]||owners[tk]!==c.id)return;seen2[tk]=true;var shares=repShares(portRep2[tk]);if(shares&&t.price){var ccy=(t.currency||"USD").toUpperCase();var fx=ccy==="USD"?1:(fxRates[ccy]||0);if(fx>0)mv+=shares*parseFloat(t.price)/fx;}});if(mv>0)repWts[port][c.id]=Math.round(mv/total*1000)/10;});var cashMV=repShares(portRep2["CASH"]);var divMV=repShares(portRep2["DIVACC"]);if(cashMV>0)repWts[port]["CASH"]=Math.round(cashMV/total*1000)/10;if(divMV>0)repWts[port]["DIVACC"]=Math.round(divMV/total*1000)/10;}
});}
function getVal(c,p){if(isRep){var rv=(repWts[p]||{})[c.id];return rv&&!isNaN(rv)?rv:0;}var tv=parseFloat((c.portWeights||{})[p]);return tv&&!isNaN(tv)?tv:0;}
var overlapCos=companies.filter(function(c){if(overlapFilter!=="All"){var fv=getVal(c,overlapFilter);if(!fv||isNaN(fv)||fv<=0)return false;}return OVERLAP_ORDER.some(function(p){return getVal(c,p)>0;});}).slice().sort(function(a,b){for(var i=0;i<OVERLAP_ORDER.length;i++){var p=OVERLAP_ORDER[i];var av=getVal(a,p);var bv=getVal(b,p);if(av!==bv)return bv-av;}return(a.name||"").localeCompare(b.name||"");});
var cashW=specialWeights["CASH"]||{};var divW=specialWeights["DIVACC"]||{};var colSums={};OVERLAP_ORDER.forEach(function(p){if(isRep){/* Rep % sums to exactly 100 by construction (all MVs divided by same total); show 100.0 when any data exists, avoiding rounding drift from summing pre-rounded row values */var hasData=Object.keys(repWts[p]||{}).length>0;colSums[p]=hasData?100.0:0;}else{var s=0;overlapCos.forEach(function(c){s+=getVal(c,p);});s+=parseFloat(cashW[p])||0;s+=parseFloat(divW[p])||0;colSums[p]=Math.round(s*10)/10;}});return(<div><div className="flex gap-2 mb-3 items-center flex-wrap"><span className="text-sm font-medium text-gray-900 dark:text-slate-100">Portfolio Overlap — {overlapCos.length} securities</span><div className="flex gap-1 ml-2">{[["target","Target %"],["rep","Rep %"]].map(function(m){return <button key={m[0]} onClick={function(){setOverlapMode(m[0]);}} className={"text-xs px-2.5 py-1 rounded-full border cursor-pointer transition-colors "+(overlapMode===m[0]?"bg-blue-100 dark:bg-blue-900/40 border-blue-300 dark:border-blue-700 text-blue-700 dark:text-blue-300 font-semibold":"border-slate-200 dark:border-slate-700 text-gray-500 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800")}>{m[1]}</button>;})}</div><div className="flex gap-1 ml-2 items-center"><span className="text-[10px] text-gray-500 dark:text-slate-400 uppercase">Filter:</span>{["All"].concat(OVERLAP_ORDER).map(function(f){var label=f==="All"?"All":OVERLAP_LABELS[f]||f;return <button key={f} onClick={function(){setOverlapFilter(f);}} className={"text-xs px-2.5 py-1 rounded-full border cursor-pointer transition-colors "+(overlapFilter===f?"bg-slate-100 dark:bg-slate-800 border-slate-400 dark:border-slate-500 text-gray-900 dark:text-slate-100 font-semibold":"border-slate-200 dark:border-slate-700 text-gray-500 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800")}>{label}</button>;})}</div><span className="text-[11px] text-gray-500 dark:text-slate-400">Cells highlighted <span className="px-1 rounded" style={{background:"rgba(220,38,38,0.18)",color:"#991b1b"}}>red</span> if higher than nearest non-blank above, <span className="px-1 rounded" style={{background:"rgba(22,101,52,0.18)",color:"#166534"}}>green</span> if lower than nearest non-blank below.</span></div><div className="overflow-x-auto"><div style={{display:"table",width:"100%",borderCollapse:"separate",borderSpacing:"0 2px"}}><div style={{display:"table-row"}} className="bg-white dark:bg-slate-950">{[["Security"],["Tier(s)"]].concat(OVERLAP_ORDER.map(function(p){return [OVERLAP_LABELS[p]];})).concat([["Port?"]]).map(function(h,i){return <div key={i} className="text-[10px] uppercase tracking-wide pb-1.5 pr-4 text-gray-500 dark:text-slate-400 font-semibold" style={{display:"table-cell"}}>{h[0]}</div>;})}</div>
{/* CASH row at top */}
<div style={{display:"table-row"}} className="bg-slate-50 dark:bg-slate-800"><div className="align-middle pr-4 py-1.5 text-sm font-semibold text-gray-900 dark:text-slate-100" style={{display:"table-cell"}}>CASH</div><div className="align-middle pr-4 py-1.5" style={{display:"table-cell"}}>--</div>{OVERLAP_ORDER.map(function(p){var v=isRep?((repWts[p]||{})["CASH"]||0):(parseFloat(cashW[p])||0);return <div key={p} className="align-middle pr-4 py-1.5 text-sm text-gray-900 dark:text-slate-100" style={{display:"table-cell"}}>{v>0?v.toFixed(1)+"%":"--"}</div>;})}<div className="align-middle pr-4 py-1.5" style={{display:"table-cell"}}>--</div></div>
{/* DIVACC row at top — only in Rep mode */}
{isRep&&<div style={{display:"table-row"}} className="bg-slate-50 dark:bg-slate-800"><div className="align-middle pr-4 py-1.5 text-sm font-semibold text-gray-900 dark:text-slate-100" style={{display:"table-cell"}}>DIVACC</div><div className="align-middle pr-4 py-1.5" style={{display:"table-cell"}}>--</div>{OVERLAP_ORDER.map(function(p){var v=(repWts[p]||{})["DIVACC"]||0;return <div key={p} className="align-middle pr-4 py-1.5 text-sm text-gray-900 dark:text-slate-100" style={{display:"table-cell"}}>{v>0?v.toFixed(1)+"%":"--"}</div>;})}<div className="align-middle pr-4 py-1.5" style={{display:"table-cell"}}>--</div></div>}
{overlapCos.map(function(c,rowIdx){var rowBgColor=tierBg(c.tier);var tiers=getTiers(c.tier);return(<div key={c.id} onClick={function(){setSelCoOrigin("portfolios");setSelCo(c);setTab("companies");setCoView("section:Valuation");}} className="hover:brightness-110 transition-all" style={{display:"table-row",cursor:"pointer"}}><div className="align-middle pr-4 py-1.5 text-sm font-medium text-gray-900 dark:text-slate-100" style={{display:"table-cell",background:dark?undefined:rowBgColor}}><span title={c.name}>{truncName(c.name,15)}</span></div><div className="align-middle pr-4 py-1.5" style={{display:"table-cell",background:dark?undefined:rowBgColor}} onClick={function(e){e.stopPropagation();}}><PortPicker active={tiers} onChange={function(v){var nt=v.join(", ");var ch={tier:nt};var s=tierToStatus(nt);if(s)ch.status=s;updateCo(c.id,ch);}} plusColor="#334155" opts={TIER_ORDER} pillStyleFn={tierPillStyle}/></div>{OVERLAP_ORDER.map(function(p,colIdx){var v=getVal(c,p);/* Find nearest non-blank row above */var pv=null;for(var k=rowIdx-1;k>=0;k--){var kv=getVal(overlapCos[k],p);if(kv>0){pv=kv;break;}}/* Find nearest non-blank row below */var nv=null;for(var k2=rowIdx+1;k2<overlapCos.length;k2++){var kv2=getVal(overlapCos[k2],p);if(kv2>0){nv=kv2;break;}}var cellBg=dark?undefined:rowBgColor;var cellColor=undefined;var cellFontWeight=undefined;if(colIdx>0&&v>0){if(pv!==null&&v>pv){cellBg=dark?"rgba(220,38,38,0.35)":"rgba(220,38,38,0.25)";cellColor=dark?"#fca5a5":"#991b1b";cellFontWeight=600;}else if(nv!==null&&nv>0&&v<nv){cellBg=dark?"rgba(22,101,52,0.35)":"rgba(22,101,52,0.25)";cellColor=dark?"#86efac":"#166534";cellFontWeight=600;}}return <div key={p} className="align-middle pr-4 py-1.5 text-sm text-gray-900 dark:text-slate-100" style={{display:"table-cell",background:cellBg,color:cellColor,fontWeight:cellFontWeight}}>{v>0?v.toFixed(1)+"%":"--"}</div>;})}<div className="align-middle pr-4 py-1.5" style={{display:"table-cell",background:dark?undefined:rowBgColor}} onClick={function(e){e.stopPropagation();}}>{(function(){var portNote=(c.portNote||"").split(/[,\s]+/).filter(Boolean);var availPortNote=PORTFOLIOS.filter(function(pp){return(c.portfolios||[]).indexOf(pp)<0;});return <PortPicker active={portNote} onChange={function(v){updateCo(c.id,{portNote:v.join(", ")});}} plusColor={dark?"#93c5fd":"#1a3a6b"} opts={availPortNote} dashedPills pillStyleFn={function(){return{bg:"transparent",color:dark?"#93c5fd":"#1a3a6b"};}}/>;})()}</div></div>);})}
{/* TOTAL sum row */}
<div style={{display:"table-row"}} className="bg-white dark:bg-slate-950"><div className="align-middle pr-4 pt-2 pb-2 text-sm font-bold text-gray-900 dark:text-slate-100 border-t-2 border-slate-200 dark:border-slate-700" style={{display:"table-cell"}}>TOTAL</div><div className="align-middle pr-4 pt-2 pb-2 border-t-2 border-slate-200 dark:border-slate-700" style={{display:"table-cell"}}>--</div>{OVERLAP_ORDER.map(function(p){var s=colSums[p];var isOk=Math.abs(s-100)<0.2;var isEmpty=s===0;return <div key={p} className="align-middle pr-4 pt-2 pb-2 text-sm font-bold border-t-2 border-slate-200 dark:border-slate-700" style={{display:"table-cell",color:isEmpty?"#94a3b8":isOk?(dark?"#4ade80":"#166534"):(dark?"#f87171":"#991b1b")}}>{isEmpty?"--":s.toFixed(1)+"%"}</div>;})}<div className="align-middle pr-4 pt-2 pb-2 border-t-2 border-slate-200 dark:border-slate-700" style={{display:"table-cell"}}>--</div></div>
</div></div>
{/* Overlap Matrices */}
{(function(){var OO=OVERLAP_ORDER;var OL=OVERLAP_LABELS;
/* Count holdings per portfolio */
var portCount={};OO.forEach(function(p){portCount[p]=companies.filter(function(c){return getVal(c,p)>0;}).length;});
/* Count overlap (both non-zero) */
function overlapCount(r,c2){return companies.filter(function(x){return getVal(x,r)>0&&getVal(x,c2)>0;}).length;}
/* Pct overlap: sum of row weights for companies also in col, div by total row weight */
function overlapPct(row,col){var totalRowW=0;var overlapW=0;companies.forEach(function(x){var rv=getVal(x,row);if(rv>0){totalRowW+=rv;if(getVal(x,col)>0)overlapW+=rv;}});return totalRowW>0?Math.round(overlapW/totalRowW*100):0;}
var totalUnique=companies.filter(function(c){return OO.some(function(p){return getVal(c,p)>0;});}).length;
var cellCls="px-3 py-1.5 text-xs text-center border border-slate-200 dark:border-slate-700";
var hdrCls="px-3 py-1.5 text-[10px] font-semibold uppercase text-center border border-slate-200 dark:border-slate-700 text-gray-500 dark:text-slate-400 bg-slate-50 dark:bg-slate-800";
return(<div className="mt-6 grid grid-cols-1 lg:grid-cols-2 gap-6">
<div><div className="text-sm font-semibold text-gray-900 dark:text-slate-100 mb-2">Securities Overlap (# of Holdings)</div>
<table className="border-collapse text-sm"><thead><tr><td className={hdrCls}>{totalUnique}</td>{OO.map(function(p){return <td key={p} className={hdrCls}>{OL[p]}</td>;})}</tr></thead><tbody>{OO.map(function(row,ri){return(<tr key={row}><td className={hdrCls}>{OL[row]}</td>{OO.map(function(col,ci){if(ci>ri)return <td key={col} className={cellCls+" text-gray-300 dark:text-slate-600"} style={{display:"table-cell"}}></td>;var n=ci===ri?portCount[row]:overlapCount(row,col);var diag=ci===ri;return <td key={col} className={cellCls+(diag?" font-bold text-gray-900 dark:text-slate-100 bg-slate-50 dark:bg-slate-800":" text-gray-700 dark:text-slate-300")}>{n}</td>;})}</tr>);})}</tbody></table></div>
<div><div className="text-sm font-semibold text-gray-900 dark:text-slate-100 mb-2">Securities Overlap (% of Portfolio)</div>
<table className="border-collapse text-sm"><thead><tr><td className={hdrCls}></td>{OO.map(function(p){return <td key={p} className={hdrCls}>{OL[p]}</td>;})}</tr></thead><tbody>{OO.map(function(row){return(<tr key={row}><td className={hdrCls}>{OL[row]}</td>{OO.map(function(col){var pct=overlapPct(row,col);var diag=row===col;var intensity=pct>0?Math.min(pct/100,1):0;var bg=diag?undefined:"rgba(37,99,235,"+intensity*0.25+")";return <td key={col} className={cellCls+(diag?" font-bold text-gray-900 dark:text-slate-100 bg-slate-50 dark:bg-slate-800":" text-gray-700 dark:text-slate-300")} style={{background:bg}}>{pct}%</td>;})}</tr>);})}</tbody></table></div>
</div>);})()}
</div>);
}
