import { useState, useRef, useEffect } from "react";

function NotesCell({company,onUpdate,T}){
  var [open,setOpen]=useState(false);var [sv,setSv]=useState(company.takeaway||"");var [lv,setLv]=useState(company.takeawayLong||"");var ref=useRef();
  useEffect(function(){if(!open)return;function h(e){if(ref.current&&!ref.current.contains(e.target))setOpen(false);}document.addEventListener("mousedown",h);return function(){document.removeEventListener("mousedown",h);};},[open]);
  var hasLong=!!(company.takeawayLong&&company.takeawayLong.trim());
  function save(){onUpdate(company.id,{takeaway:sv,takeawayLong:lv});setOpen(false);}
  return(<div style={{position:"relative"}} onClick={function(e){e.stopPropagation();}}><div style={{display:"flex",alignItems:"center",gap:4}}><span onClick={function(){setOpen(true);setSv(company.takeaway||"");setLv(company.takeawayLong||"");}} style={{fontSize:11,color:company.takeaway?T.textSec:T.border,fontStyle:company.takeaway?"normal":"italic",display:"block",maxWidth:150,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",cursor:"pointer",borderBottom:"1px dashed "+T.borderSec}}>{company.takeaway||"add note..."}</span>{hasLong&&<span title="Extended notes" style={{fontSize:9,cursor:"pointer"}} onClick={function(){setOpen(true);setSv(company.takeaway||"");setLv(company.takeawayLong||"");}}>📝</span>}</div>{open&&(<div ref={ref} style={{position:"absolute",top:"100%",left:0,zIndex:300,background:T.bg,border:"1px solid "+T.border,borderRadius:8,padding:12,width:300,boxShadow:"0 8px 24px rgba(0,0,0,0.15)"}}><div style={{fontSize:11,color:T.textSec,marginBottom:4}}>Short takeaway</div><input value={sv} onChange={function(e){setSv(e.target.value);}} style={{width:"100%",boxSizing:"border-box",fontSize:12,padding:"5px 8px",borderRadius:5,border:"1px solid "+T.border,background:T.bgSec,color:T.text,marginBottom:8}}/><div style={{fontSize:11,color:T.textSec,marginBottom:4}}>Extended notes</div><textarea value={lv} onChange={function(e){setLv(e.target.value);}} rows={5} style={{width:"100%",boxSizing:"border-box",fontSize:12,padding:"5px 8px",borderRadius:5,border:"1px solid "+T.border,background:T.bgSec,color:T.text,resize:"vertical",fontFamily:"inherit",lineHeight:1.6,marginBottom:8}}/><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><span onClick={function(){setOpen(false);}} style={{fontSize:12,color:T.textSec,cursor:"pointer",padding:"4px 8px"}}>Cancel</span><button onClick={save} style={{fontSize:12,padding:"4px 12px",fontWeight:500}}>Save</button></div></div>)}</div>);
}

export default NotesCell;
